export default {
  white: 'white',
  border: '#E2E2E2',
  text: '#343434',
  blue: 'blue',
  textLight: '#797979',
  offWhite: '#F0F0F0',
  black: 'black',
  yellow: 'yellow',
  grey:'grey',
  brown: 'brown',
  green: 'green',
  pink: 'pink',
  purple: 'purple',
  red: 'red',
};